# Generated by Django 2.2.1 on 2019-06-20 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 23, 7, 1, 885467, tzinfo=utc)),
        ),
    ]
