# Generated by Django 2.2.1 on 2019-06-23 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190620_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
