# Generated by Django 2.2.1 on 2019-06-20 22:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='upload/')),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2019, 6, 20, 22, 55, 5, 303061, tzinfo=utc))),
                ('bump_date', models.DateTimeField(default=datetime.datetime(2019, 6, 20, 22, 55, 5, 303081, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
