# Generated by Django 2.2.1 on 2019-06-20 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='bump_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
