# Generated by Django 2.2.1 on 2019-06-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190620_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='static/pages/download.svg', upload_to='upload/'),
        ),
    ]
